MyBlog/MyBlog/Controllers/BlogCommentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using MyBlog.Data;
using MyBlog.Models;
using System.Diagnostics;
using System.Security.Claims;
using X.PagedList;

namespace MyBlog.Controllers
{
    [Authorize(Roles = "Admin, Editor, User")]
    public class BlogCommentsController : Controller
    {
        //Veritabanı Modeline Erişim

        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomUser> _userManager;

        public BlogCommentsController(ApplicationDbContext context, UserManager<CustomUser> userManager)

        {
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
            public async Task<IActionResult> Details(int postId)
        {
            var comments = await _context.Comments
                .Where(comment => comment.BlogPostId == postId)
                .Include(comment => comment.User)
                .ToListAsync();

            var blogPost = await _context.BlogPosts.FirstOrDefaultAsync(b => b.Id == postId);

            return PartialView("_CommentsPartial", comments);
        }

        public async Task<IActionResult> GetComments(int blogId, int page )
        {
            var comments = await _context.Comments
                .Where(c => c.BlogPostId == blogId)
                .Include(c => c.User)
                .OrderByDescending(c => c.CreatedAt)
                .Skip((page - 1) * 5)
                .Take(5)
                .ToListAsync();

            return PartialView("_CommentsPartial", comments); // PartialView ile HTML döndür
        }


        [HttpPost]

        public async Task<IActionResult> AddComment(string content, int postId)
        {
            if (string.IsNullOrWhiteSpace(content))
            {
                return Json(new { success = false, message = "Yorum içeriği boş olamaz." });
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var addComment = new AddComment
            {
                Content = content,
                BlogPostId = postId,
                UserId = userId,
                CreatedAt = DateTime.Now
            };

            // AddComment modelini Comment modeline dönüştürüyoruz
            var comment = new Comment
            {
                Content = addComment.Content,
                BlogPostId = addComment.BlogPostId,
                UserId = addComment.UserId,
                CreatedAt = addComment.CreatedAt
                // İlişkiler buraya eklenmiyor, çünkü sadece ihtiyacımız olan alanları kullanıyoruz
            };

            _context.Comments.Add(comment);
            await _context.SaveChangesAsync();

            return Json(new { success = true, message = "Yorum başarıyla eklendi.", addComment = comment });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteComment(int id, string returnUrl)
        {
            var comment = await _context.Comments.FindAsync(id);

            if (comment == null)
            {
                return Json(new { success = false, message = "Yorum bulunamadı." });
            }

            // Sadece mevcut kullanıcı kendi yorumunu silebilir
            var currentUser = await _userManager.GetUserAsync(User);
            var isAdmin = User.IsInRole("Admin");
            if (comment.UserId != currentUser.Id && !isAdmin)
            {
                return Forbid(); // 403 Forbidden döndür
            }

            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();

            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Details", "BlogPost", new { id = comment.BlogPostId }); // yorumun bağlı olduğu gönderiye geri dön
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public async Task<IActionResult> MyComments()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var comments = await _context.Comments
                .Include(c => c.BlogPost)
                .Include(c => c.User)
                .Where(c => c.UserId == userId)
                .ToListAsync();


            return View(comments);
        }


        [HttpGet]
        public async Task<IActionResult> EditComment(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var isAdmin = User.IsInRole("Admin");
            if (comment.UserId != currentUser.Id && !isAdmin)
            {
                return Forbid();
            }

            var editComment = new EditComment
            {
                Id = comment.Id,
                CommentId = comment.Id,
                Text = comment.Content,

            };

            return View(editComment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditComment(int id, EditComment editComment)
        {
            if (id != editComment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var comment = await _context.Comments.FindAsync(editComment.CommentId);
                    if (comment == null)
                    {
                        return NotFound();
                    }

                    comment.Content = editComment.Text;

                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(editComment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MyComments));
            }
            return View(editComment);
        }

        [HttpGet]
        public async Task<IActionResult> EditCommentDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var isAdmin = User.IsInRole("Admin");
            if (comment.UserId != currentUser.Id && !isAdmin)
            {
                return Forbid();
            }

            var editComment = new EditComment
            {
                Id = comment.Id,
                CommentId = comment.Id,
                Text = comment.Content,

            };
            return PartialView(editComment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCommentDetails(int id, EditComment editComment)
        {
            if (id != editComment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var comment = await _context.Comments.FindAsync(editComment.CommentId);
                    if (comment == null)
                    {
                        return NotFound();
                    }

                    comment.Content = editComment.Text;

                    _context.Update(comment);
                    await _context.SaveChangesAsync();

                    return Json(new { success = true, postId = comment.BlogPostId });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(editComment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }

            return PartialView(editComment);
        }

        private bool CommentExists(int id)
        {
            return _context.Comments.Any(e => e.Id == id);
        }
    }
}

MyBlog/MyBlog/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MyBlog.Data;
using MyBlog.Models;
using System.Data;

namespace MyBlog.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CustomUser> _userManager;


        public ProfileController(ApplicationDbContext context, UserManager<CustomUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound("Kullanıcı Bulunamadı");
            }

            var blogPosts = await _context.BlogPosts.Where(bp => bp.UserId == user.FullName).ToListAsync();

            var viewModel = new ProfileViewModel
            {
                Id = user.Id,
                FullName = user.FullName,
                Email = user.Email,
                DateOfBirth = user.DateOfBirth,
                Gender = user.Gender,
                Username = user.UserName,
                ProfilePictureUrl = user.ProfilePictureUrl,
                BlogPost = blogPosts
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)

            {
                return NotFound("Kullanıcı Bulunamadı");
            }
            var viewModel = new ProfileViewModel
            {
                Id = user.Id,
                FullName = user.FullName,
                Email = user.Email,
                DateOfBirth = user.DateOfBirth,
                Gender = user.Gender,
                Username = user.UserName,
                ProfilePictureUrl = user.ProfilePictureUrl
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(ProfileViewModel Model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("402", "Kayıt İletilemedi");
                //new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
                return View();
            }

            var cUser = _context.Users.Find(Model.Id);

            if (cUser == null)
            {
                ModelState.AddModelError("404", "Kullanıcı Bulunamadı");
                //new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
                return View();
            }

            cUser.FullName = Model.FullName;
            cUser.Email = Model.Email;
            cUser.Gender = Model.Gender;
            cUser.DateOfBirth = Model.DateOfBirth;
            cUser.UserName = Model.Username;



            if (Model.ProfilePicture != null)
            {
                var filePath = Path.Combine(@"wwwroot/images/profiles", Model.ProfilePicture.FileName);

                var directory = Path.GetDirectoryName(filePath);
                if (Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await Model.ProfilePicture.CopyToAsync(stream);

                }
                cUser.ProfilePictureUrl = $"/images/profiles/{Model.ProfilePicture.FileName}";
            }

            var result = await _userManager.UpdateAsync(cUser);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");

            }


            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(User);
        }

        //Parola Değiştirme
        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            var result = await _userManager.ChangePasswordAsync(user, model.CurrentPassword, model.NewPassword);
            if (result.Succeeded)
            {
                await _userManager.UpdateSecurityStampAsync(user);
                return RedirectToAction("Edit");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult ChangePasswordConfirmation()
        {
            return View();
        }




    }
}

MyBlog/MyBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBlog</title>
    <link rel='stylesheet' href='~/Template/css/woocommerce-layout.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/Template/css/woocommerce-smallscreen.css' type='text/css' media='only screen and (max-width: 768px)' />
    <link rel='stylesheet' href='~/Template/css/woocommerce.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/Template/css/font-awesome.min.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/Template/style.css' type='text/css' media='all' />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Oswald:400,500,700%7CRoboto:400,500,700%7CHerr+Von+Muellerhoff:400,500,700%7CQuattrocento+Sans:400,500,700' type='text/css' media='all' />
    <link rel='stylesheet' href='~/Template/css/easy-responsive-shortcodes.css' type='text/css' media='all' />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 
</head>
<style>
    .site-title{
        margin:0px;
    }

    .site-header {
        margin: 0px;
        .search-container .search-container
    }

    .search-container {
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 0 auto;
    }

    #logoutForm {
        display: flex;
        justify-content: center; /* Yatay ortalama */
        align-items: center; /* Dikey ortalama */
    }

    .nav-link.text-dark {
        text-align: center; /* Metni ortalar */
    }

    
</style>

<body class="home page page-template page-template-template-portfolio page-template-template-portfolio-php">
    <div id="page">
        <div class="container-fluid">
            <header id="masthead" class="site-header">
                <div class="site-branding">
                    <h1 class="site-title"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">MyBlog</a></h1>
                </div>
                <nav id="site-navigation" class="main-navigation">
                    <button class="menu-toggle">Menu</button>

                    <div class="menu-menu-1-container" >

                        <ul id="menu-menu-1" class="menu nav-menu" >

                            <li> <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>

                            @if (User.IsInRole("Admin") || User.IsInRole("Editor") || User.IsInRole("User"))
                            {
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profil</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="BlogPost" asp-action="Index">İçerik</a></li>
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="BlogComments" asp-action="MyComments">Yorumlarım</a></li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
                            {
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="BlogPost" asp-action="Create">Yazı Oluştur</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="BlogPost" asp-action="Read">Bloglarım</a></li>
                            }

                            @if (User.IsInRole("Admin"))
                            {
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Yönetim</a></li>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole("Editor") || User.IsInRole("User"))
                            {
                                <li>
                                    <a class="nav-link text-dark">Ara</a>
                                    <ul class="sub-menu">
                                        <!-- Arama çubuğu başlangıcı -->
                                        <div class="search-container">
                                        <form asp-controller="BlogPost" asp-action="Search" method="get" class="form-inline my-2 my-lg-0">
                                            <input class="form-control search-input" type="search" placeholder="Başlık veya Yazar Ara" aria-label="Ara" name="SearchTerm">
                                            
                                            </form>
                                        </div>
                                        <!-- Arama çubuğu bitişi -->
                                    </ul>
                                </li>

                                <!-- Arama sonuçları başlangıcı -->
                                @if (!string.IsNullOrEmpty(ViewBag.SearchTerm))
                                {
                                    <div class="search-results">
                                        <h4>Arama Sonuçları</h4>
                                        <ul>
                                            @foreach (var post in ViewBag.SearchResults)
                                            {
                                                <li>
                                                    <a href="@Url.Action("Details", "User", new { id = post.Id })">@post.Title</a>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                }
                                <!-- Arama sonuçları bitişi -->
                            }

                            <li><a <partial name="_LoginPartial"/></a></li>
                        </ul>
                        

                    </div>

                </nav>

            </header>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="colophon" class="site-footer">
        <div class="container">
            <div class="site-info">
                <h1 style="font-family: 'Herr Von Muellerhoff';color: #ccc;font-weight:300;text-align: center;margin-bottom:0;margin-top:0;line-height:1.4;font-size: 46px;">MyBlog</h1>
                <a target="blank" href="user/index">&copy; MyBlog - 2024</a>
            </div>
        </div>
    </footer>
   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- #page -->
    @* <script src='~/Template/js/jquery.js'></script> *@
    <script src='~/Template/js/plugins.js'></script>
    <script src='~/Template/js/scripts.js'></script>
    <script src='~/Template/js/masonry.pkgd.min.js'></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>